[[news]]
date = "2020-08"
content = "Starting my undergraduate at the Hainan University"

[[news]]
date = "2023-09"
content = "Our work has been accepted by Microbial genomics journal 🎉"

[[news]]
date = "2024-02"
content = "Our work has been accepted by BMC genomics journal 🎉"

[[news]]
date = "2023-09"
content = "Starting my Master at the Ocean University of China."
