type = "card"
title = "Teaching"
description = "Class I have taught or assisted with."

[[items]]
title = "2022 Biotechology class Ⅲ"
subtitle = "Class Teacher's Assistant"
date = "2022-2023"
content = "I formed the freshman class group, guided incoming students through enrollment, and assisted in electing the new class committee. Established a communication bridge between teachers and freshmen, aiding teachers in managing freshmen effectively. Additionally, assisted freshmen in adapting to university life, covering aspects such as academics, daily life, and ideological orientation.)."
tags = ["Undergraduate", "Biotechology"]
