type = "card"
title = "奖项"
description = "我获得的荣誉与奖项。"

[[items]]
title = "海南大学年度人物"
subtitle = "海南大学"
date = "2024.06"
content = "该奖项为海南大学本科生最高荣誉称号，每年不超过30人获得此称号。"

[[items]]
title = "第九届全国大学生生命科学竞赛·全国一等奖"
subtitle = "全国大学生生命科学竞赛委员会"
date = "2024.08"
content = "在该比赛中，我主要探究了6mA修饰在两株致病菌基因组上的分布特征，及其与基因表达和功能的关联的研究。该比赛由全国大学生生命科学竞赛委员会组织，是教育部认可的大学生A类竞赛。该项目获得了此比赛的最高级别奖项，获奖率不超过2%。"

[[items]]
title = "华数杯全国大学生数学建模竞赛·全国三等奖"
subtitle = "中国未来研究会"
date = "2023.08"
content = "在该比赛中，主要利用多种模型探讨了母亲身心健康对婴儿生长发育的影响,深入分析了二者之间的关联。在该比赛中获得了全国三等奖，其获奖率不超过30%。"

[[items]]
title = "全国大学生英语作文大赛·三等奖"
subtitle = "全国大学生英语作文大赛组织委员会"
date = "2023.06"
content = "该比赛以中英互译形式考核，考验其英语基础能力。该比赛仅有4,000人获得三等奖，整体获奖率仅为10%。"

[[items]]
title = "第十三届全国大学生数学竞赛·三等奖"
subtitle = "中国数学会"
date = "2021.12"
content = "在这项考察高等数学知识的竞赛中，我荣获了三等奖。本次竞赛的获奖率约为11%。"
