[[news]]
date = "2020-08"
content = "就读于海南大学大学生物技术专业"

[[news]]
date = "2023-09"
content = "参与的第一个工作发表于Microbial genomics期刊。"

[[news]]
date = "2024-02"
content = "以独立一作身份发表sci论文于BMC genomics期刊。"

[[news]]
date = "2024-08"
content = "就读于中国海洋大学生物学专业。"
